version: '3.8'

services:
  ai-world:
    image: 192.168.1.7:5000/ai-world:detection2-2a7724d
    ports:
      - "7860:7860"
    volumes:
      - /data/.cache:/root/.cache
      - /data/.deepface:/root/.deepface
      - /data/.torch:/root/.torch
      - /data/gradio:/tmp/gradio
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always