[program:rag]
command=/bin/bash -c 'source /root/miniconda/bin/activate base && python /home/ubuntu/hg/ai/app.py'
directory=/home/ubuntu/hg/ai/
autostart=true
autorestart=true
stderr_logfile=/var/log/rag.err.log
stdout_logfile=/var/log/rag.out.log
user=root
