# 使用指定的基础镜像
FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

# 更新 apt-get 并安装依赖
# RUN apt-get update && \
#     apt-get install -y --no-install-recommends git python3-opencv && \
#     rm -rf /var/lib/apt/lists/*

RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirrors.aliyun.com/ubuntu/|g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends python3-opencv && \
    apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements-docker.txt /workspace
# 安装 Python 依赖
RUN pip install --no-cache-dir -r requirements-docker.txt

# 设置环境变量
ENV PYTHONUNBUFFERED=1
