# 使用指定的基础镜像
FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

# 更新 apt-get 并安装依赖
RUN apt-get update && \
    apt-get install -y --no-install-recommends && \
    apt-get install -y git && \
    apt-get install -y python3-opencv 

COPY ./requirements-docker.txt /workspace
# 安装 Python 依赖
RUN pip install --no-cache-dir -r requirements-docker.txt

# 设置环境变量
ENV PYTHONUNBUFFERED=1
